# Generated by Django 5.2.9 on 2025-12-21 06:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PartiallyPickedAssembly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(db_index=True, max_length=50, verbose_name='Номер заказа')),
                ('task_id', models.CharField(db_index=True, max_length=100, verbose_name='ID сборки')),
                ('status_str', models.CharField(default='PARTIALLY_PICKED', max_length=50, verbose_name='Статус сборки')),
                ('assembly_zone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Зона сборки')),
                ('assembler', models.CharField(blank=True, max_length=255, null=True, verbose_name='Сборщик')),
                ('products_data', models.JSONField(default=list, verbose_name='Данные о товарах')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время отправки')),
                ('source_system', models.CharField(default='assembly_tracker', max_length=100, verbose_name='Источник данных')),
                ('products_count', models.IntegerField(default=0, verbose_name='Количество несобранных товаров')),
                ('total_missing_quantity', models.IntegerField(default=0, verbose_name='Общее количество недостающих штук')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания записи')),
            ],
            options={
                'verbose_name': 'Частично собранная сборка',
                'verbose_name_plural': 'Частично собранные сборки',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['order_number', 'timestamp'], name='particles_p_order_n_e3e4f7_idx'), models.Index(fields=['assembler', 'timestamp'], name='particles_p_assembl_3ba3d2_idx')],
            },
        ),
    ]
