# Generated by Django 5.2.9 on 2025-12-21 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('particles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partiallypickedassembly',
            name='products_data',
        ),
        migrations.CreateModel(
            name='PartiallyPickedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lm_code', models.CharField(db_index=True, max_length=50, verbose_name='LM код товара')),
                ('department_id', models.CharField(blank=True, max_length=10, null=True, verbose_name='ID отдела')),
                ('title', models.TextField(blank=True, null=True, verbose_name='Название товара')),
                ('image_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL изображения')),
                ('quantity', models.IntegerField(default=0, verbose_name='Требуемое количество')),
                ('collected_quantity', models.IntegerField(default=0, verbose_name='Собранное количество')),
                ('missing_quantity', models.IntegerField(default=0, verbose_name='Недостающее количество')),
                ('source', models.CharField(blank=True, max_length=100, null=True, verbose_name='Источник')),
                ('is_critical', models.BooleanField(default=False, verbose_name='Критический товар')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления записи')),
                ('assembly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='particles.partiallypickedassembly', verbose_name='Сборка')),
            ],
            options={
                'verbose_name': 'Несобранный товар',
                'verbose_name_plural': 'Несобранные товары',
                'ordering': ['-missing_quantity'],
                'indexes': [models.Index(fields=['lm_code', 'missing_quantity'], name='particles_p_lm_code_32cfc5_idx'), models.Index(fields=['department_id', 'missing_quantity'], name='particles_p_departm_448910_idx')],
            },
        ),
    ]
