# Generated by Django 5.2.9 on 2025-12-21 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('particles', '0002_remove_partiallypickedassembly_products_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partiallypickedassembly',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Время обновления записи'),
        ),
        migrations.AddConstraint(
            model_name='partiallypickedassembly',
            constraint=models.UniqueConstraint(fields=('order_number', 'task_id'), name='unique_assembly_order_task'),
        ),
        migrations.AddConstraint(
            model_name='partiallypickedproduct',
            constraint=models.UniqueConstraint(fields=('assembly', 'lm_code', 'quantity', 'collected_quantity'), name='unique_product_in_assembly'),
        ),
    ]
