# Generated by Django 5.2.9 on 2025-12-22 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('particles', '0003_partiallypickedassembly_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partiallypickedassembly',
            name='black_list',
            field=models.BooleanField(default=False, verbose_name='игнорирование'),
        ),
    ]
