# Generated by Django 5.2.9 on 2025-12-23 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('particles', '0004_partiallypickedassembly_black_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='partiallypickedproduct',
            name='black_list',
            field=models.BooleanField(default=False, verbose_name='игнорирование'),
        ),
    ]
