# Generated by Django 5.2.9 on 2025-12-21 10:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PageVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40)),
                ('url', models.URLField(max_length=500)),
                ('full_url', models.URLField(max_length=1000)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('referer', models.URLField(blank=True, max_length=500, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('method', models.CharField(default='GET', max_length=10)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Посещение страницы',
                'verbose_name_plural': 'Посещения страниц',
                'indexes': [models.Index(fields=['url', 'timestamp'], name='home_pagevi_url_c4e316_idx'), models.Index(fields=['timestamp'], name='home_pagevi_timesta_8ece19_idx'), models.Index(fields=['session_key', 'timestamp'], name='home_pagevi_session_6d4e7b_idx')],
            },
        ),
    ]
